[build]
  command = "npm run build"
  publish = "dist"

# Form detection settings
[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

# Enable form detection
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Form handling settings  
[forms]
  # This ensures forms are processed correctly
